// 1. 키보드 스위치 원본 데이터 (72개)
var swDb = [
    { brand: "Cherry", name: "MX 저소음 적축", tags: ["저소음", "리니어"], weight: "45g" },
    { brand: "Cherry", name: "MX 저소음 흑축", tags: ["저소음", "리니어"], weight: "60g" },
    { brand: "Outemu", name: "저소음 피치축 V3", tags: ["저소음", "리니어"], weight: "40g" },
    { brand: "Outemu", name: "저소음 라임축 V3", tags: ["저소음", "택타일"], weight: "35g" },
    { brand: "TTC", name: "저소음 월백축", tags: ["저소음", "택타일"], weight: "42g" },
    { brand: "Gateron", name: "저소음 갈축", tags: ["저소음", "택타일"], weight: "55g" },
    { brand: "Kailh", name: "저소음 고래축", tags: ["저소음", "택타일"], weight: "40g" },
    { brand: "Haimu", name: "위스퍼축", tags: ["저소음", "리니어"], weight: "47g" },
    { brand: "TTC", name: "저소음 프로즌축 V2", tags: ["저소음", "리니어"], weight: "39g" },
    { brand: "삼성전자", name: "DT35", tags: ["멤브레인"], weight: "-" },
    { brand: "로지텍", name: "K120", tags: ["멤브레인"], weight: "-" },
    { brand: "로지텍", name: "G213 Prodigy", tags: ["멤브레인"], weight: "-" },
    { brand: "레이저", name: "Cynosa V2", tags: ["멤브레인"], weight: "-" },
    { brand: "Wooting", name: "Lekker L60축", tags: ["자석축", "리니어"], weight: "40g" },
    { brand: "Wooting", name: "Lekker L45축", tags: ["자석축", "리니어"], weight: "30g" },
    { brand: "Gateron", name: "마그네틱 제이드축", tags: ["자석축", "리니어"], weight: "30g" },
    { brand: "Gateron", name: "마그네틱 오렌지축", tags: ["자석축", "리니어"], weight: "38g" },
    { brand: "DrunkDeer", name: "마그네틱축", tags: ["자석축", "리니어"], weight: "30g" },
    { brand: "Geonworks", name: "RAW 마그네틱축", tags: ["자석축", "리니어"], weight: "30g" },
    { brand: "Gateron", name: "마그네틱 옥축(Jade) Pro", tags: ["자석축", "리니어"], weight: "36g" },
    { brand: "Outemu", name: "Silent Honey HE축", tags: ["자석축", "저소음", "리니어"], weight: "35g" },
    { brand: "TTC", name: "마그네틱 바나나축", tags: ["자석축", "택타일"], weight: "45g" },
    { brand: "Gamakay", name: "피닉스축", tags: ["저소음", "리니어"], weight: "40g" },
    { brand: "MATHEW", name: "저소음 자석축", tags: ["자석축", "저소음", "리니어"], weight: "30g" },
    { brand: "Glorious", name: "Raptor HE (글로리어스 랩터)", tags: ["클릭", "자석축"], weight: "40g" },
    { brand: "Outemu", name: "Blue Magnetic (오테뮤 청축 자석축)", tags: ["클릭", "자석축"], weight: "50g" },
    { brand: "Glorious", name: "Panda HE (글로리어스 판다)", tags: ["택타일", "자석축"], weight: "45g" },
    { brand: "Cherry", name: "MX 청축", tags: ["클릭"], weight: "50g" },
    { brand: "Gateron", name: "청축 Pro", tags: ["클릭"], weight: "60g" },
    { brand: "Kailh", name: "박스 백축", tags: ["클릭"], weight: "45g" },
    { brand: "Kailh", name: "박스 네이비축", tags: ["클릭"], weight: "60g" },
    { brand: "Outemu", name: "청축", tags: ["클릭"], weight: "60g" },
    { brand: "Razer", name: "녹축", tags: ["클릭"], weight: "50g" },
    { brand: "TTC", name: "골드 청축", tags: ["클릭"], weight: "50g" },
    { brand: "Kailh", name: "박스 제이드축", tags: ["클릭"], weight: "50g" },
    { brand: "Kailh", name: "백부엉이축", tags: ["클릭"], weight: "46g" },
    { brand: "Haimu", name: "미드나이트축", tags: ["리니어"], weight: "50g" },
    { brand: "Cherry", name: "MX 적축", tags: ["리니어"], weight: "45g" },
    { brand: "Cherry", name: "MX 흑축", tags: ["리니어"], weight: "60g" },
    { brand: "KTT", name: "바다소금축(레몬)", tags: ["리니어"], weight: "45g" },
    { brand: "KTT", name: "강백축 V3", tags: ["리니어"], weight: "43g" },
    { brand: "Gateron", name: "황축 Pro", tags: ["리니어"], weight: "50g" },
    { brand: "HMX", name: "히아신스 V2", tags: ["리니어"], weight: "45g" },
    { brand: "HMX", name: "치즈축", tags: ["리니어"], weight: "43g" },
    { brand: "HMX", name: "파도축", tags: ["리니어"], weight: "43g" },
    { brand: "LEOBOG", name: "회목축(그레이우드) V4", tags: ["리니어"], weight: "40g" },
    { brand: "LEOBOG", name: "신월축", tags: ["리니어"], weight: "42g" },
    { brand: "Akko", name: "V3 크림 블루 프로축", tags: ["택타일"], weight: "45g" },
    { brand: "TTC", name: "스피드 은축", tags: ["리니어"], weight: "45g" },
    { brand: "HMX", name: "마카롱축", tags: ["리니어"], weight: "42g" },
    { brand: "HMX", name: "신해축", tags: ["리니어"], weight: "37g" },
    { brand: "KTT", name: "스트로베리축", tags: ["리니어"], weight: "43g" },
    { brand: "Gateron", name: "CJ축", tags: ["리니어"], weight: "50g" },
    { brand: "SP-Star", name: "유성백축", tags: ["리니어"], weight: "43g" },
    { brand: "LEOBOG", name: "스페이스축", tags: ["리니어"], weight: "38g" },
    { brand: "LEOBOG", name: "님버스축(Nimbus)", tags: ["리니어"], weight: "40g" },
    { brand: "SWAGKEY", name: "오울랩 네온축", tags: ["리니어"], weight: "43g" },
    { brand: "LEOBOG", name: "황금축 V3", tags: ["리니어"], weight: "34g" },
    { brand: "VGN", name: "자스민축", tags: ["리니어"], weight: "45g" },
    { brand: "MCHOSE", name: "말차라떼축", tags: ["리니어"], weight: "47g" },
    { brand: "Cherry", name: "MX 갈축", tags: ["택타일"], weight: "45g" },
    { brand: "Drop", name: "홀리판다축", tags: ["택타일"], weight: "50g" },
    { brand: "Gazzew", name: "보바 U4T축", tags: ["택타일"], weight: "50g" },
    { brand: "Gateron", name: "갈축 Pro", tags: ["택타일"], weight: "55g" },
    { brand: "Kailh", name: "박스 갈축", tags: ["택타일"], weight: "50g" },
    { brand: "LEOBOG", name: "얼음영혼축(빙혼축)", tags: ["택타일"], weight: "30g" },
    { brand: "Outemu", name: "갈축", tags: ["택타일"], weight: "50g" },
    { brand: "TTC", name: "골드 갈축", tags: ["택타일"], weight: "55g" },
    { brand: "SP-Star", name: "유성오렌지축", tags: ["택타일"], weight: "43g" },
    { brand: "KTT", name: "말차축 (Matcha)", tags: ["택타일"], weight: "40g" },
    { brand: "Geonworks", name: "브라운 RAW축", tags: ["택타일"], weight: "41g" },
    { brand: "Gateron", name: "베이비 캥거루축 (BBK)", tags: ["택타일"], weight: "59g" }
];

// 2. 마우스 원본 데이터 (51개)
var msDb = [
    { brand: "VXE", name: "R1 Pro Max", conn: ["유선", "무선"], buttons: 2, weight: 54, hz: "4K" },
    { brand: "VXE", name: "R1 SE", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 51, hz: "1K" },
    { brand: "VXE", name: "R1 SE+", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 55, hz: "2K" },
    { brand: "VGN", name: "F1 Moba", conn: ["유선", "무선"], buttons: 2, weight: 55, hz: "4K" },
    { brand: "Logitech", name: "G Pro X Superlight 2", conn: ["유선", "무선"], buttons: 2, weight: 60, hz: "8K" },
    { brand: "Logitech", name: "G Pro X Superlight", conn: ["유선", "무선"], buttons: 2, weight: 63, hz: "1K" },
    { brand: "Logitech", name: "G304", conn: ["무선"], buttons: 3, weight: 99, hz: "1K" },
    { brand: "Logitech", name: "G502 X Plus", conn: ["유선", "무선"], buttons: 8, weight: 106, hz: "1K" },
    { brand: "Logitech", name: "G102", conn: ["유선"], buttons: 3, weight: 85, hz: "1K" },
    { brand: "Logitech", name: "G703 Hero", conn: ["유선", "무선"], buttons: 3, weight: 95, hz: "1K" },
    { brand: "Logitech", name: "G903 Hero", conn: ["유선", "무선"], buttons: 8, weight: 110, hz: "1K" },
    { brand: "Razer", name: "Viper V3 Pro", conn: ["유선", "무선"], buttons: 2, weight: 54, hz: "8K" },
    { brand: "Razer", name: "Viper V2 Pro", conn: ["유선", "무선"], buttons: 2, weight: 58, hz: "8K" },
    { brand: "Razer", name: "DeathAdder V3 Pro", conn: ["유선", "무선"], buttons: 2, weight: 63, hz: "8K" },
    { brand: "Razer", name: "DeathAdder V3", conn: ["유선"], buttons: 2, weight: 59, hz: "8K" },
    { brand: "Razer", name: "Basilisk V3 Pro", conn: ["유선", "무선", "블루투스"], buttons: 7, weight: 112, hz: "8K" },
    { brand: "Razer", name: "Cobra Pro", conn: ["유선", "무선", "블루투스"], buttons: 4, weight: 77, hz: "8K" },
    { brand: "Razer", name: "Orochi V2", conn: ["무선", "블루투스"], buttons: 3, weight: 73, hz: "1K" },
    { brand: "Pulsar", name: "X2V2", conn: ["유선", "무선"], buttons: 2, weight: 53, hz: "4K" },
    { brand: "Pulsar", name: "X2H", conn: ["유선", "무선"], buttons: 2, weight: 54, hz: "4K" },
    { brand: "Pulsar", name: "Xlite V3", conn: ["유선", "무선"], buttons: 2, weight: 55, hz: "4K" },
    { brand: "Lamzu", name: "Atlantis OG V2", conn: ["유선", "무선"], buttons: 2, weight: 55, hz: "4K" },
    { brand: "Lamzu", name: "Thorn", conn: ["유선", "무선"], buttons: 2, weight: 52, hz: "4K" },
    { brand: "Lamzu", name: "Maya", conn: ["유선", "무선"], buttons: 2, weight: 45, hz: "4K" },
    { brand: "Ninjutso", name: "Sora V2", conn: ["유선", "무선"], buttons: 2, weight: 39, hz: "8K" },
    { brand: "Ninjutso", name: "Sora 4K", conn: ["유선", "무선"], buttons: 2, weight: 47, hz: "4K" },
    { brand: "Zowie", name: "U2", conn: ["유선", "무선"], buttons: 2, weight: 60, hz: "1K" },
    { brand: "Zowie", name: "EC2-CW", conn: ["유선", "무선"], buttons: 2, weight: 77, hz: "1K" },
    { brand: "Zowie", name: "EC2-C", conn: ["유선"], buttons: 2, weight: 73, hz: "1K" },
    { brand: "EndgameGear", name: "OP1 8K", conn: ["유선"], buttons: 2, weight: 50, hz: "8K" },
    { brand: "EndgameGear", name: "OP1we", conn: ["유선", "무선"], buttons: 2, weight: 58, hz: "1K" },
    { brand: "EndgameGear", name: "XM2we", conn: ["유선", "무선"], buttons: 2, weight: 63, hz: "1K" },
    { brand: "ASUS", name: "ROG Harpe Ace", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 54, hz: "8K" },
    { brand: "ASUS", name: "ROG Keris II", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 54, hz: "8K" },
    { brand: "ASUS", name: "ROG Gladius III", conn: ["유선", "무선", "블루투스"], buttons: 3, weight: 79, hz: "1K" },
    { brand: "WLmouse", name: "Beast X", conn: ["유선", "무선"], buttons: 2, weight: 39, hz: "4K" },
    { brand: "WLmouse", name: "Beast X Mini", conn: ["유선", "무선"], buttons: 2, weight: 34, hz: "4K" },
    { brand: "WLmouse", name: "Beast X Max", conn: ["유선", "무선"], buttons: 2, weight: 42, hz: "8K" },
    { brand: "GWolves", name: "HTS Plus 4K", conn: ["유선", "무선"], buttons: 2, weight: 49, hz: "4K" },
    { brand: "GWolves", name: "HTX 4K", conn: ["유선", "무선"], buttons: 2, weight: 43, hz: "4K" },
    { brand: "Glorious", name: "Model O 2", conn: ["유선", "무선", "블루투스"], buttons: 3, weight: 68, hz: "1K" },
    { brand: "Glorious", name: "Model D 2", conn: ["유선", "무선", "블루투스"], buttons: 3, weight: 71, hz: "1K" },
    { brand: "SteelSeries", name: "Aerox 3 Wireless", conn: ["유선", "무선", "블루투스"], buttons: 3, weight: 68, hz: "1K" },
    { brand: "SteelSeries", name: "Prime Wireless", conn: ["유선", "무선"], buttons: 2, weight: 80, hz: "1K" },
    { brand: "Roccat", name: "Kone Pro Air", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 75, hz: "1K" },
    { brand: "TurtleBeach", name: "Burst II Air", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 47, hz: "1K" },
    { brand: "Keychron", name: "M4", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 35, hz: "4K" },
    { brand: "Corsair", name: "M75 Air", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 60, hz: "2K" },
    { brand: "Corsair", name: "Harpoon Wireless", conn: ["유선", "무선", "블루투스"], buttons: 3, weight: 99, hz: "1K" },
    { brand: "Fantech", name: "Aria XD7", conn: ["유선", "무선", "블루투스"], buttons: 2, weight: 59, hz: "1K" },
    { brand: "Zaopin", name: "Z1 Pro", conn: ["유선", "무선"], buttons: 2, weight: 46, hz: "4K" }
];